package db.migration;

import org.flywaydb.core.Flyway;
import org.junit.jupiter.api.Test;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;
import static org.junit.jupiter.api.Assertions.assertThrows;

class TermsMigrationTest {

    private static final String URL =
            "jdbc:h2:mem:terms-migration;MODE=MySQL;DB_CLOSE_DELAY=-1";

    @Test
    void 약관_4종을_생성하고_UserTerms_termId를_외래키로_연결한다() throws Exception {
        createUserTermsTable();

        Flyway.configure()
                .dataSource(URL, "sa", "")
                .baselineOnMigrate(true)
                .baselineVersion("48")
                .load()
                .migrate();

        try (Connection connection = DriverManager.getConnection(URL, "sa", "")) {
            assertThat(tableNames(connection))
                    .contains("terms")
                    .doesNotContain("Terms");
            assertThat(terms(connection)).containsExactly(
                    "1:만 14세 이상 확인:MANDATORY",
                    "2:서비스 이용약관:MANDATORY",
                    "3:개인정보 수집 및 이용 동의:MANDATORY",
                    "4:광고성 정보 수신 및 마케팅 활용 동의:OPTIONAL"
            );
            assertThat(userTerms(connection)).containsExactly(
                    "10:1:true",
                    "10:4:true"
            );
            assertThat(hasTermsForeignKey(connection)).isTrue();
            assertThat(firstTermsContent(connection))
                    .contains("## 2. [필수] 서비스 이용약관", "제1조 (목적)");

            assertThrows(SQLException.class, () -> insertUnknownTermsId(connection));
        }
    }

    private void createUserTermsTable() throws Exception {
        try (Connection connection = DriverManager.getConnection(URL, "sa", "");
             Statement statement = connection.createStatement()) {
            statement.execute("""
                    CREATE TABLE UserTerms (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        userId BIGINT NOT NULL,
                        termId BIGINT NOT NULL,
                        isAgreed BOOLEAN NOT NULL,
                        agreedAt TIMESTAMP NOT NULL,
                        createdAt TIMESTAMP NOT NULL,
                        updatedAt TIMESTAMP NOT NULL,
                        CONSTRAINT uk_user_terms UNIQUE (userId, termId)
                    )
                    """);
            statement.execute("""
                    INSERT INTO UserTerms
                        (userId, termId, isAgreed, agreedAt, createdAt, updatedAt)
                    VALUES (10, 1, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                           (10, 4, FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                           (10, 5, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
                    """);
        }
    }

    private List<String> terms(Connection connection) throws Exception {
        List<String> terms = new ArrayList<>();
        try (Statement statement = connection.createStatement();
             ResultSet resultSet = statement.executeQuery(
                     "SELECT \"termId\", \"name\", \"type\" FROM \"terms\" "
                             + "ORDER BY \"termId\"")) {
            while (resultSet.next()) {
                terms.add(resultSet.getLong(1) + ":" + resultSet.getString(2)
                        + ":" + resultSet.getString(3));
            }
        }
        return terms;
    }

    private List<String> tableNames(Connection connection) throws Exception {
        List<String> tableNames = new ArrayList<>();
        try (ResultSet tables = connection.getMetaData().getTables(
                connection.getCatalog(), connection.getSchema(), "%", new String[]{"TABLE"})) {
            while (tables.next()) {
                tableNames.add(tables.getString("TABLE_NAME"));
            }
        }
        return tableNames;
    }

    private List<String> userTerms(Connection connection) throws Exception {
        List<String> userTerms = new ArrayList<>();
        try (Statement statement = connection.createStatement();
             ResultSet resultSet = statement.executeQuery(
                     "SELECT userId, termId, isAgreed FROM UserTerms "
                             + "ORDER BY userId, termId")) {
            while (resultSet.next()) {
                userTerms.add(resultSet.getLong(1) + ":" + resultSet.getLong(2)
                        + ":" + resultSet.getBoolean(3));
            }
        }
        return userTerms;
    }

    private String firstTermsContent(Connection connection) throws Exception {
        try (Statement statement = connection.createStatement();
             ResultSet resultSet = statement.executeQuery(
                    "SELECT \"content\" FROM \"terms\" WHERE \"termId\" = 2")) {
            assertThat(resultSet.next()).isTrue();
            return resultSet.getString(1);
        }
    }

    private boolean hasTermsForeignKey(Connection connection) throws Exception {
        try (ResultSet keys = connection.getMetaData().getImportedKeys(
                connection.getCatalog(), connection.getSchema(), "USERTERMS")) {
            while (keys.next()) {
                if ("terms".equals(keys.getString("PKTABLE_NAME"))) {
                    return true;
                }
            }
        }
        return false;
    }

    private void insertUnknownTermsId(Connection connection) throws Exception {
        try (Statement statement = connection.createStatement()) {
            statement.execute("""
                    INSERT INTO UserTerms
                        (userId, termId, isAgreed, agreedAt, createdAt, updatedAt)
                    VALUES (20, 99, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
                    """);
        }
    }
}
