package db.migration;

import org.flywaydb.core.api.migration.BaseJavaMigration;
import org.flywaydb.core.api.migration.Context;

import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.ResultSet;
import java.sql.Statement;

public class V12__create_session_recruitment_views extends BaseJavaMigration {
    @Override
    public void migrate(Context context) throws Exception {
        Connection connection = context.getConnection();
        if (tableExists(connection, "session_recruitment_views")) return;
        String recruitmentTable = findTable(connection, "session_recruitment");
        String userTable = findTable(connection, "user");
        if (recruitmentTable == null || userTable == null) return;
        String recruitmentIdColumn = findColumn(
                connection, recruitmentTable, "session_recruitment_id"
        );
        String userIdColumn = findColumn(connection, userTable, "id");
        if (recruitmentIdColumn == null || userIdColumn == null) return;
        boolean mysql = connection.getMetaData().getDatabaseProductName().toLowerCase().contains("mysql");
        String id = mysql ? "BIGINT NOT NULL AUTO_INCREMENT" : "BIGINT GENERATED BY DEFAULT AS IDENTITY";
        try (Statement statement = connection.createStatement()) {
            statement.execute("CREATE TABLE " + q("session_recruitment_views", mysql) + " ("
                    + q("session_recruitment_view_id", mysql) + " " + id + ", "
                    + q("session_recruitment_id", mysql) + " BIGINT NOT NULL, "
                    + q("user_id", mysql) + " BIGINT NOT NULL, "
                    + q("created_at", mysql) + " TIMESTAMP NOT NULL, "
                    + q("updated_at", mysql) + " TIMESTAMP NOT NULL, "
                    + "PRIMARY KEY (" + q("session_recruitment_view_id", mysql) + "), "
                    + "CONSTRAINT " + q("uk_session_recruitment_view", mysql) + " UNIQUE ("
                    + q("session_recruitment_id", mysql) + ", " + q("user_id", mysql) + "), "
                    + "CONSTRAINT " + q("fk_recruitment_view_recruitment", mysql) + " FOREIGN KEY ("
                    + q("session_recruitment_id", mysql) + ") REFERENCES "
                    + q(recruitmentTable, mysql) + " (" + q(recruitmentIdColumn, mysql) + ") ON DELETE CASCADE, "
                    + "CONSTRAINT " + q("fk_recruitment_view_user", mysql) + " FOREIGN KEY ("
                    + q("user_id", mysql) + ") REFERENCES " + q(userTable, mysql) + " (" + q(userIdColumn, mysql) + ") ON DELETE CASCADE)"
            );
        }
    }

    private boolean tableExists(Connection connection, String expected) throws Exception {
        return findTable(connection, expected) != null;
    }

    private String findTable(Connection connection, String expected) throws Exception {
        DatabaseMetaData metadata = connection.getMetaData();
        try (ResultSet tables = metadata.getTables(connection.getCatalog(), connection.getSchema(), "%", new String[]{"TABLE"})) {
            while (tables.next()) {
                String name = tables.getString("TABLE_NAME");
                if (expected.equalsIgnoreCase(name)) return name;
            }
        }
        return null;
    }
    private String findColumn(Connection connection, String table, String expected) throws Exception {
        try (ResultSet columns = connection.getMetaData().getColumns(
                connection.getCatalog(), connection.getSchema(), table, "%")) {
            while (columns.next()) {
                String name = columns.getString("COLUMN_NAME");
                if (expected.equalsIgnoreCase(name)) return name;
            }
        }
        return null;
    }
    private String q(String name, boolean mysql) { return mysql ? "`" + name + "`" : "\"" + name + "\""; }
}
