package db.migration;

import org.flywaydb.core.api.migration.BaseJavaMigration;
import org.flywaydb.core.api.migration.Context;
import java.sql.*;

public class V14__create_chat_messages extends BaseJavaMigration {
    @Override public void migrate(Context context) throws Exception {
        Connection c = context.getConnection();
        if (table(c, "chat_messages") != null) return;
        String rooms = table(c, "chat_rooms"), users = table(c, "user");
        if (rooms == null || users == null) return;
        String roomId = column(c, rooms, "chat_room_id"), userId = column(c, users, "id");
        if (roomId == null || userId == null) return;
        boolean mysql = c.getMetaData().getDatabaseProductName().toLowerCase().contains("mysql");
        String id = mysql ? "BIGINT NOT NULL AUTO_INCREMENT" : "BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL";
        String sql = "CREATE TABLE " + q("chat_messages", mysql) + " ("
                + q("chat_message_id", mysql) + " " + id + ", "
                + q("chat_room_id", mysql) + " BIGINT NOT NULL, "
                + q("sender_id", mysql) + " BIGINT NOT NULL, "
                + q("content", mysql) + " VARCHAR(2000) NOT NULL, "
                + q("read_at", mysql) + " TIMESTAMP NULL, "
                + q("created_at", mysql) + " TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, "
                + q("updated_at", mysql) + " TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, "
                + "PRIMARY KEY (" + q("chat_message_id", mysql) + "), "
                + "CONSTRAINT " + q("fk_chat_message_room", mysql) + " FOREIGN KEY (" + q("chat_room_id", mysql)
                + ") REFERENCES " + q(rooms, mysql) + " (" + q(roomId, mysql) + ") ON DELETE CASCADE, "
                + "CONSTRAINT " + q("fk_chat_message_sender", mysql) + " FOREIGN KEY (" + q("sender_id", mysql)
                + ") REFERENCES " + q(users, mysql) + " (" + q(userId, mysql) + "))";
        try (Statement s = c.createStatement()) { s.execute(sql); }
    }
    private String table(Connection c, String expected) throws Exception {
        try (ResultSet r = c.getMetaData().getTables(c.getCatalog(), c.getSchema(), "%", new String[]{"TABLE"})) {
            while (r.next()) if (expected.equalsIgnoreCase(r.getString("TABLE_NAME"))) return r.getString("TABLE_NAME");
        } return null;
    }
    private String column(Connection c, String table, String expected) throws Exception {
        try (ResultSet r = c.getMetaData().getColumns(c.getCatalog(), c.getSchema(), table, "%")) {
            while (r.next()) if (expected.equalsIgnoreCase(r.getString("COLUMN_NAME"))) return r.getString("COLUMN_NAME");
        } return null;
    }
    private String q(String v, boolean mysql) { return mysql ? "`" + v + "`" : "\"" + v + "\""; }
}
