package db.migration;

import org.flywaydb.core.api.migration.BaseJavaMigration;
import org.flywaydb.core.api.migration.Context;

import java.sql.*;

public class V15__create_chat_rooms extends BaseJavaMigration {
    @Override
    public void migrate(Context context) throws Exception {
        Connection connection = context.getConnection();
        if (findTable(connection, "chat_rooms") != null) return;
        String userTable = findTable(connection, "user");
        String recruitmentTable = findTable(connection, "session_recruitment");
        String applicationTable = findTable(connection, "session_applications");
        if (userTable == null || recruitmentTable == null || applicationTable == null) return;
        String userId = findColumn(connection, userTable, "id");
        String recruitmentId = findColumn(connection, recruitmentTable, "session_recruitment_id");
        String applicationId = findColumn(connection, applicationTable, "session_application_id");
        if (userId == null || recruitmentId == null || applicationId == null) return;
        boolean mysql = connection.getMetaData().getDatabaseProductName().toLowerCase().contains("mysql");
        String generatedId = mysql ? "BIGINT NOT NULL AUTO_INCREMENT"
                : "BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL";
        String sql = "CREATE TABLE " + q("chat_rooms", mysql) + " ("
                + q("chat_room_id", mysql) + " " + generatedId + ", "
                + q("context_type", mysql) + " VARCHAR(30) NOT NULL, "
                + q("sender_id", mysql) + " BIGINT NOT NULL, "
                + q("recipient_id", mysql) + " BIGINT NOT NULL, "
                + q("session_recruitment_id", mysql) + " BIGINT NULL, "
                + q("session_application_id", mysql) + " BIGINT NULL, "
                + q("created_at", mysql) + " TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, "
                + q("updated_at", mysql) + " TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, "
                + "PRIMARY KEY (" + q("chat_room_id", mysql) + "), "
                + "CONSTRAINT " + q("fk_chat_sender", mysql) + " FOREIGN KEY (" + q("sender_id", mysql)
                + ") REFERENCES " + q(userTable, mysql) + " (" + q(userId, mysql) + "), "
                + "CONSTRAINT " + q("fk_chat_recipient", mysql) + " FOREIGN KEY (" + q("recipient_id", mysql)
                + ") REFERENCES " + q(userTable, mysql) + " (" + q(userId, mysql) + "), "
                + "CONSTRAINT " + q("fk_chat_recruitment", mysql) + " FOREIGN KEY (" + q("session_recruitment_id", mysql)
                + ") REFERENCES " + q(recruitmentTable, mysql) + " (" + q(recruitmentId, mysql) + "), "
                + "CONSTRAINT " + q("fk_chat_application", mysql) + " FOREIGN KEY (" + q("session_application_id", mysql)
                + ") REFERENCES " + q(applicationTable, mysql) + " (" + q(applicationId, mysql) + "))";
        try (Statement statement = connection.createStatement()) { statement.execute(sql); }
    }

    private String findTable(Connection c, String expected) throws Exception {
        try (ResultSet rs = c.getMetaData().getTables(c.getCatalog(), c.getSchema(), "%", new String[]{"TABLE"})) {
            while (rs.next()) if (expected.equalsIgnoreCase(rs.getString("TABLE_NAME"))) return rs.getString("TABLE_NAME");
        }
        return null;
    }
    private String findColumn(Connection c, String table, String expected) throws Exception {
        try (ResultSet rs = c.getMetaData().getColumns(c.getCatalog(), c.getSchema(), table, "%")) {
            while (rs.next()) if (expected.equalsIgnoreCase(rs.getString("COLUMN_NAME"))) return rs.getString("COLUMN_NAME");
        }
        return null;
    }
    private String q(String value, boolean mysql) { return mysql ? "`" + value + "`" : "\"" + value + "\""; }
}
