package db.migration;

import org.flywaydb.core.api.migration.BaseJavaMigration;
import org.flywaydb.core.api.migration.Context;
import java.sql.*;

public class V20__create_user_blocks extends BaseJavaMigration {
    @Override
    public void migrate(Context context) throws Exception {
        Connection connection = context.getConnection();
        if (findTable(connection, "user_blocks") != null) return;
        String userTable = findTable(connection, "user");
        if (userTable == null) return;
        String userId = findColumn(connection, userTable, "id");
        if (userId == null) return;

        boolean mysql = connection.getMetaData().getDatabaseProductName().toLowerCase().contains("mysql");
        String generatedId = mysql ? "BIGINT NOT NULL AUTO_INCREMENT"
                : "BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL";
        String sql = "CREATE TABLE " + q("user_blocks", mysql) + " ("
                + q("user_block_id", mysql) + " " + generatedId + ", "
                + q("blocker_id", mysql) + " BIGINT NOT NULL, "
                + q("blocked_id", mysql) + " BIGINT NOT NULL, "
                + q("created_at", mysql) + " TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, "
                + q("updated_at", mysql) + " TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, "
                + "PRIMARY KEY (" + q("user_block_id", mysql) + "), "
                + "CONSTRAINT " + q("uk_user_blocks_blocker_blocked", mysql) + " UNIQUE ("
                + q("blocker_id", mysql) + ", " + q("blocked_id", mysql) + "), "
                + "CONSTRAINT " + q("fk_user_blocks_blocker", mysql) + " FOREIGN KEY (" + q("blocker_id", mysql)
                + ") REFERENCES " + q(userTable, mysql) + " (" + q(userId, mysql) + "), "
                + "CONSTRAINT " + q("fk_user_blocks_blocked", mysql) + " FOREIGN KEY (" + q("blocked_id", mysql)
                + ") REFERENCES " + q(userTable, mysql) + " (" + q(userId, mysql) + "))";
        try (Statement statement = connection.createStatement()) { statement.execute(sql); }
    }

    private String findTable(Connection c, String expected) throws Exception {
        try (ResultSet rs = c.getMetaData().getTables(c.getCatalog(), c.getSchema(), "%", new String[]{"TABLE"})) {
            while (rs.next()) if (expected.equalsIgnoreCase(rs.getString("TABLE_NAME"))) return rs.getString("TABLE_NAME");
        }
        return null;
    }

    private String findColumn(Connection c, String table, String expected) throws Exception {
        try (ResultSet rs = c.getMetaData().getColumns(c.getCatalog(), c.getSchema(), table, "%")) {
            while (rs.next()) if (expected.equalsIgnoreCase(rs.getString("COLUMN_NAME"))) return rs.getString("COLUMN_NAME");
        }
        return null;
    }

    private String q(String value, boolean mysql) { return mysql ? "`" + value + "`" : "\"" + value + "\""; }
}
