package db.migration;

import org.flywaydb.core.api.migration.BaseJavaMigration;
import org.flywaydb.core.api.migration.Context;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;

public class V27__create_session_recruitment_search_keywords extends BaseJavaMigration {

    @Override
    public void migrate(Context context) throws Exception {
        Connection connection = context.getConnection();
        if (findTable(connection, "session_recruitment_search_keywords") != null) return;

        String userTable = findTable(connection, "user");
        if (userTable == null) return;
        String userIdColumn = findColumn(connection, userTable, "id", "user_id");
        if (userIdColumn == null) return;

        boolean mysql = connection.getMetaData().getDatabaseProductName()
                .toLowerCase().contains("mysql");
        String id = mysql
                ? "BIGINT NOT NULL AUTO_INCREMENT"
                : "BIGINT GENERATED BY DEFAULT AS IDENTITY";
        try (Statement statement = connection.createStatement()) {
            statement.execute("CREATE TABLE " + q("session_recruitment_search_keywords", mysql)
                    + " (" + q("session_recruitment_search_keyword_id", mysql) + " " + id + ", "
                    + q("user_id", mysql) + " BIGINT NOT NULL, "
                    + q("keyword", mysql) + " VARCHAR(100) NOT NULL, "
                    + q("searched_at", mysql) + " TIMESTAMP NOT NULL, "
                    + "PRIMARY KEY (" + q("session_recruitment_search_keyword_id", mysql) + "), "
                    + "CONSTRAINT " + q("uk_recruitment_search_keyword_user_keyword", mysql)
                    + " UNIQUE (" + q("user_id", mysql) + ", " + q("keyword", mysql) + "), "
                    + "CONSTRAINT " + q("fk_recruitment_search_keyword_user", mysql)
                    + " FOREIGN KEY (" + q("user_id", mysql) + ") REFERENCES "
                    + q(userTable, mysql) + " (" + q(userIdColumn, mysql) + ") ON DELETE CASCADE)"
            );
        }
    }

    private String findColumn(Connection connection, String table, String... expectedNames)
            throws Exception {
        try (ResultSet columns = connection.getMetaData().getColumns(
                connection.getCatalog(), connection.getSchema(), table, "%")) {
            while (columns.next()) {
                String name = columns.getString("COLUMN_NAME");
                for (String expected : expectedNames) {
                    if (expected.equalsIgnoreCase(name)) return name;
                }
            }
        }
        return null;
    }

    private String findTable(Connection connection, String expected) throws Exception {
        try (ResultSet tables = connection.getMetaData().getTables(
                connection.getCatalog(), connection.getSchema(), "%", new String[]{"TABLE"})) {
            while (tables.next()) {
                String name = tables.getString("TABLE_NAME");
                if (expected.equalsIgnoreCase(name)) return name;
            }
        }
        return null;
    }

    private String q(String value, boolean mysql) {
        return mysql ? "`" + value + "`" : "\"" + value + "\"";
    }
}
