package db.migration;

import org.flywaydb.core.api.migration.BaseJavaMigration;
import org.flywaydb.core.api.migration.Context;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;

public class V28__add_session_application_activities_and_careers extends BaseJavaMigration {
    @Override
    public void migrate(Context context) throws Exception {
        Connection connection = context.getConnection();
        String applicationTable = findTable(connection, "session_applications");
        if (applicationTable == null) return;
        String applicationId = findColumn(
                connection, applicationTable, "session_application_id");
        if (applicationId == null) return;
        boolean mysql = connection.getMetaData().getDatabaseProductName()
                .toLowerCase().contains("mysql");
        String identity = mysql ? "BIGINT NOT NULL AUTO_INCREMENT"
                : "BIGINT GENERATED BY DEFAULT AS IDENTITY";

        try (Statement statement = connection.createStatement()) {
            if (findColumn(connection, applicationTable, "one_line_intro") == null) {
                statement.execute("ALTER TABLE " + q(applicationTable, mysql)
                        + " ADD COLUMN " + q("one_line_intro", mysql) + " VARCHAR(100)");
            }
            if (findTable(connection, "session_application_activities") == null) {
                statement.execute("CREATE TABLE " + q("session_application_activities", mysql)
                        + " (" + q("session_application_id", mysql) + " BIGINT NOT NULL, "
                        + q("activity", mysql) + " VARCHAR(30) NOT NULL, "
                        + "CONSTRAINT " + q("fk_application_activity", mysql) + " FOREIGN KEY ("
                        + q("session_application_id", mysql) + ") REFERENCES "
                        + q(applicationTable, mysql) + " (" + q(applicationId, mysql)
                        + ") ON DELETE CASCADE)");
            }
            if (findTable(connection, "session_application_careers") == null) {
                statement.execute("CREATE TABLE " + q("session_application_careers", mysql)
                        + " (" + q("session_application_career_id", mysql) + " " + identity + ", "
                        + q("session_application_id", mysql) + " BIGINT NOT NULL, "
                        + q("name", mysql) + " VARCHAR(100) NOT NULL, "
                        + q("period", mysql) + " VARCHAR(100) NOT NULL, "
                        + q("description", mysql) + " VARCHAR(500), PRIMARY KEY ("
                        + q("session_application_career_id", mysql) + "), CONSTRAINT "
                        + q("fk_application_career", mysql) + " FOREIGN KEY ("
                        + q("session_application_id", mysql) + ") REFERENCES "
                        + q(applicationTable, mysql) + " (" + q(applicationId, mysql)
                        + ") ON DELETE CASCADE)");
            }
        }
    }

    private String findTable(Connection connection, String expected) throws Exception {
        try (ResultSet tables = connection.getMetaData().getTables(
                connection.getCatalog(), connection.getSchema(), "%", new String[]{"TABLE"})) {
            while (tables.next()) {
                String name = tables.getString("TABLE_NAME");
                if (expected.equalsIgnoreCase(name)) return name;
            }
        }
        return null;
    }

    private String findColumn(Connection connection, String table, String expected)
            throws Exception {
        try (ResultSet columns = connection.getMetaData().getColumns(
                connection.getCatalog(), connection.getSchema(), table, "%")) {
            while (columns.next()) {
                String name = columns.getString("COLUMN_NAME");
                if (expected.equalsIgnoreCase(name)) return name;
            }
        }
        return null;
    }

    private String q(String value, boolean mysql) {
        return mysql ? "`" + value + "`" : "\"" + value + "\"";
    }
}
