package db.migration;

import org.flywaydb.core.api.migration.BaseJavaMigration;
import org.flywaydb.core.api.migration.Context;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;

public class V42__create_band_invite_link extends BaseJavaMigration {

    private static final String TABLE_NAME = "band_invite_link";

    @Override
    public void migrate(Context context) throws Exception {
        Connection connection = context.getConnection();

        if (findTable(connection, TABLE_NAME) != null) {
            return;
        }

        String bandTable = findTable(connection, "Band");

        if (bandTable == null) {
            return;
        }

        String bandIdColumn = findColumn(connection, bandTable, "id");

        if (bandIdColumn == null) {
            return;
        }

        boolean mysql = connection.getMetaData()
                .getDatabaseProductName()
                .toLowerCase()
                .contains("mysql");

        String idDefinition = mysql
                ? "BIGINT NOT NULL AUTO_INCREMENT"
                : "BIGINT GENERATED BY DEFAULT AS IDENTITY";

        String dateTimeType = mysql
                ? "DATETIME(6)"
                : "TIMESTAMP(6)";

        String sql = "CREATE TABLE " + quote(TABLE_NAME, mysql) + " ("
                + quote("id", mysql) + " " + idDefinition + ", "
                + quote("band_id", mysql) + " BIGINT NOT NULL, "
                + quote("token", mysql) + " VARCHAR(64) NOT NULL, "
                + quote("expires_at", mysql) + " " + dateTimeType + " NOT NULL, "
                + quote("created_at", mysql)
                + " TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, "
                + quote("updated_at", mysql)
                + " TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, "

                + "PRIMARY KEY (" + quote("id", mysql) + "), "

                + "CONSTRAINT " + quote(
                "uk_band_invite_link_band",
                mysql
        )
                + " UNIQUE (" + quote("band_id", mysql) + "), "

                + "CONSTRAINT " + quote(
                "uk_band_invite_link_token",
                mysql
        )
                + " UNIQUE (" + quote("token", mysql) + "), "

                + "CONSTRAINT " + quote(
                "fk_band_invite_link_band",
                mysql
        )
                + " FOREIGN KEY (" + quote("band_id", mysql) + ") "
                + "REFERENCES " + quote(bandTable, mysql)
                + " (" + quote(bandIdColumn, mysql) + ") "
                + "ON DELETE CASCADE"
                + ")";

        try (Statement statement = connection.createStatement()) {
            statement.execute(sql);
        }
    }

    private String findTable(
            Connection connection,
            String expectedName
    ) throws Exception {
        try (ResultSet tables = connection.getMetaData().getTables(
                connection.getCatalog(),
                connection.getSchema(),
                "%",
                new String[]{"TABLE"}
        )) {
            while (tables.next()) {
                String tableName = tables.getString("TABLE_NAME");

                if (expectedName.equalsIgnoreCase(tableName)) {
                    return tableName;
                }
            }
        }

        return null;
    }

    private String findColumn(
            Connection connection,
            String tableName,
            String expectedName
    ) throws Exception {
        try (ResultSet columns = connection.getMetaData().getColumns(
                connection.getCatalog(),
                connection.getSchema(),
                tableName,
                "%"
        )) {
            while (columns.next()) {
                String columnName = columns.getString("COLUMN_NAME");

                if (expectedName.equalsIgnoreCase(columnName)) {
                    return columnName;
                }
            }
        }

        return null;
    }

    private String quote(String identifier, boolean mysql) {
        return mysql
                ? "`" + identifier + "`"
                : "\"" + identifier + "\"";
    }
}
