package db.migration;

import org.flywaydb.core.api.migration.BaseJavaMigration;
import org.flywaydb.core.api.migration.Context;

import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.Timestamp;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class V49__create_terms extends BaseJavaMigration {

    private static final Pattern SECTION_HEADING = Pattern.compile(
            "(?m)^## ([1-4])\\. \\[(필수|선택)] (.+)$"
    );

    private static final List<TermsSeed> SEEDS = List.of(
            new TermsSeed(1L, 1, "만 14세 이상 확인", "MANDATORY"),
            new TermsSeed(2L, 2, "서비스 이용약관", "MANDATORY"),
            new TermsSeed(3L, 3, "개인정보 수집 및 이용 동의", "MANDATORY"),
            new TermsSeed(4L, 4, "광고성 정보 수신 및 마케팅 활용 동의", "OPTIONAL")
    );

    @Override
    public void migrate(Context context) throws Exception {
        Connection connection = context.getConnection();
        boolean mysql = connection.getMetaData().getDatabaseProductName()
                .toLowerCase(Locale.ROOT)
                .contains("mysql");

        String termsTable = findTable(connection, "terms", "Terms");
        if (termsTable == null) {
            termsTable = "terms";
            createTermsTable(connection, termsTable, mysql);
        }

        seedTerms(connection, termsTable, mysql);
        migrateLegacyUserTermsIds(connection, mysql);
        addUserTermsForeignKey(connection, termsTable, mysql);
    }

    private void createTermsTable(Connection connection, String table, boolean mysql)
            throws Exception {
        String identity = mysql
                ? "BIGINT NOT NULL AUTO_INCREMENT"
                : "BIGINT GENERATED BY DEFAULT AS IDENTITY";
        String contentType = mysql ? "TEXT" : "CLOB";

        try (Statement statement = connection.createStatement()) {
            statement.execute("CREATE TABLE " + q(table, mysql) + " ("
                    + q("termId", mysql) + " " + identity + ", "
                    + q("name", mysql) + " VARCHAR(255) NOT NULL, "
                    + q("content", mysql) + " " + contentType + " NOT NULL, "
                    + q("type", mysql) + " VARCHAR(20) NOT NULL, "
                    + q("createdAt", mysql) + " TIMESTAMP NOT NULL, "
                    + q("updatedAt", mysql) + " TIMESTAMP NOT NULL, "
                    + "PRIMARY KEY (" + q("termId", mysql) + "))");
        }
    }

    private void seedTerms(Connection connection, String table, boolean mysql) throws Exception {
        List<String> sections = parseSections(readTermsDocument());
        LocalDateTime now = LocalDateTime.now();
        String sql = "INSERT INTO " + q(table, mysql) + " ("
                + q("termId", mysql) + ", " + q("name", mysql) + ", "
                + q("content", mysql) + ", " + q("type", mysql) + ", "
                + q("createdAt", mysql) + ", " + q("updatedAt", mysql)
                + ") VALUES (?, ?, ?, ?, ?, ?)";

        for (TermsSeed seed : SEEDS) {
            if (exists(connection, table, seed.termId(), mysql)) {
                continue;
            }
            try (PreparedStatement statement = connection.prepareStatement(sql)) {
                statement.setLong(1, seed.termId());
                statement.setString(2, seed.name());
                statement.setString(3, sections.get(seed.sectionNumber() - 1));
                statement.setString(4, seed.type());
                statement.setTimestamp(5, Timestamp.valueOf(now));
                statement.setTimestamp(6, Timestamp.valueOf(now));
                statement.executeUpdate();
            }
        }
    }

    private boolean exists(Connection connection, String table, long termId, boolean mysql)
            throws Exception {
        String sql = "SELECT 1 FROM " + q(table, mysql)
                + " WHERE " + q("termId", mysql) + " = ?";
        try (PreparedStatement statement = connection.prepareStatement(sql)) {
            statement.setLong(1, termId);
            try (ResultSet resultSet = statement.executeQuery()) {
                return resultSet.next();
            }
        }
    }

    private void migrateLegacyUserTermsIds(Connection connection, boolean mysql) throws Exception {
        String userTermsTable = findTable(connection, "UserTerms", "user_terms");
        if (userTermsTable == null) {
            return;
        }

        String termIdColumn = findColumn(connection, userTermsTable, "termId", "term_id");
        if (termIdColumn == null) {
            return;
        }

        // 기존 4번 서비스 알림 동의는 폐기하고, 5번 마케팅 동의를 새 4번으로 이동한다.
        try (Statement statement = connection.createStatement()) {
            statement.executeUpdate("DELETE FROM " + q(userTermsTable, mysql)
                    + " WHERE " + q(termIdColumn, mysql) + " = 4");
            statement.executeUpdate("UPDATE " + q(userTermsTable, mysql)
                    + " SET " + q(termIdColumn, mysql) + " = 4"
                    + " WHERE " + q(termIdColumn, mysql) + " = 5");
        }
    }

    private void addUserTermsForeignKey(
            Connection connection,
            String termsTable,
            boolean mysql
    ) throws Exception {
        String userTermsTable = findTable(connection, "UserTerms", "user_terms");
        if (userTermsTable == null || hasTermsForeignKey(connection, userTermsTable, termsTable)) {
            return;
        }

        String termIdColumn = findColumn(connection, userTermsTable, "termId", "term_id");
        if (termIdColumn == null) {
            return;
        }
        validateExistingTermIds(connection, userTermsTable, termIdColumn, termsTable, mysql);

        try (Statement statement = connection.createStatement()) {
            statement.execute("ALTER TABLE " + q(userTermsTable, mysql)
                    + " ADD CONSTRAINT " + q("fk_user_terms_terms", mysql)
                    + " FOREIGN KEY (" + q(termIdColumn, mysql) + ") REFERENCES "
                    + q(termsTable, mysql) + " (" + q("termId", mysql) + ")");
        }
    }

    private void validateExistingTermIds(
            Connection connection,
            String userTermsTable,
            String termIdColumn,
            String termsTable,
            boolean mysql
    ) throws Exception {
        String sql = "SELECT COUNT(*) FROM " + q(userTermsTable, mysql) + " u LEFT JOIN "
                + q(termsTable, mysql) + " t ON u." + q(termIdColumn, mysql)
                + " = t." + q("termId", mysql) + " WHERE t." + q("termId", mysql)
                + " IS NULL";
        try (Statement statement = connection.createStatement();
             ResultSet resultSet = statement.executeQuery(sql)) {
            resultSet.next();
            if (resultSet.getLong(1) > 0) {
                throw new IllegalStateException(
                        "UserTerms에 Terms와 연결할 수 없는 termId가 존재합니다."
                );
            }
        }
    }

    private boolean hasTermsForeignKey(Connection connection, String table, String termsTable)
            throws Exception {
        DatabaseMetaData metadata = connection.getMetaData();
        try (ResultSet keys = metadata.getImportedKeys(
                connection.getCatalog(), connection.getSchema(), table)) {
            while (keys.next()) {
                if (termsTable.equalsIgnoreCase(keys.getString("PKTABLE_NAME"))) {
                    return true;
                }
            }
        }
        return false;
    }

    private List<String> parseSections(String document) {
        Matcher matcher = SECTION_HEADING.matcher(document);
        List<Integer> starts = new ArrayList<>();
        while (matcher.find()) {
            starts.add(matcher.start());
        }
        if (starts.size() != 4) {
            throw new IllegalStateException("약관 원문에서 4개 섹션을 찾지 못했습니다.");
        }

        List<String> sections = new ArrayList<>();
        for (int i = 0; i < starts.size(); i++) {
            int end = i + 1 < starts.size() ? starts.get(i + 1) : document.length();
            sections.add(document.substring(starts.get(i), end).trim());
        }
        return sections;
    }

    private String readTermsDocument() throws IOException {
        try (InputStream input = getClass().getResourceAsStream("/db/terms/terms-v1.md")) {
            if (input == null) {
                throw new IllegalStateException("약관 원문 리소스를 찾을 수 없습니다.");
            }
            return new String(input.readAllBytes(), StandardCharsets.UTF_8);
        }
    }

    private String findTable(Connection connection, String... expectedNames) throws Exception {
        try (ResultSet tables = connection.getMetaData().getTables(
                connection.getCatalog(), connection.getSchema(), "%", new String[]{"TABLE"})) {
            while (tables.next()) {
                String name = tables.getString("TABLE_NAME");
                for (String expected : expectedNames) {
                    if (expected.equalsIgnoreCase(name)) {
                        return name;
                    }
                }
            }
        }
        return null;
    }

    private String findColumn(Connection connection, String table, String... expectedNames)
            throws Exception {
        try (ResultSet columns = connection.getMetaData().getColumns(
                connection.getCatalog(), connection.getSchema(), table, "%")) {
            while (columns.next()) {
                String name = columns.getString("COLUMN_NAME");
                for (String expected : expectedNames) {
                    if (expected.equalsIgnoreCase(name)) {
                        return name;
                    }
                }
            }
        }
        return null;
    }

    private String q(String value, boolean mysql) {
        return mysql ? "`" + value.replace("`", "``") + "`"
                : "\"" + value.replace("\"", "\"\"") + "\"";
    }

    private record TermsSeed(
            long termId,
            int sectionNumber,
            String name,
            String type
    ) {
    }
}
