package db.migration;

import org.flywaydb.core.api.migration.BaseJavaMigration;
import org.flywaydb.core.api.migration.Context;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.ArrayList;

/**
 * 밴드 검수 플로우 도입.
 * 1) Band.status 컬럼 추가 — 기존 밴드는 전부 ACCEPTED로 백필
 * 2) name 단일 UNIQUE 제거 → (name, status) 복합 UNIQUE로 교체
 *    (검수 중 PENDING 밴드와 기존 ACCEPTED 밴드의 동명 공존 허용)
 * 3) 검수 요청 감사 테이블 band_create_request 생성
 */
public class V54__add_band_status_and_create_request_table extends BaseJavaMigration {

    private static final String REQUEST_TABLE = "band_create_request";
    private static final String COMPOSITE_UNIQUE = "uk_band_name_status";

    @Override
    public void migrate(Context context) throws Exception {
        Connection connection = context.getConnection();

        String bandTable = findTable(connection, "Band");
        if (bandTable == null) {
            return;
        }

        boolean mysql = connection.getMetaData()
                .getDatabaseProductName()
                .toLowerCase()
                .contains("mysql");

        addStatusColumn(connection, bandTable, mysql);
        replaceNameUnique(connection, bandTable, mysql);
        createRequestTable(connection, bandTable, mysql);
    }

    private void addStatusColumn(
            Connection connection,
            String bandTable,
            boolean mysql
    ) throws Exception {
        if (findColumn(connection, bandTable, "status") != null) {
            return;
        }

        execute(connection, "ALTER TABLE " + quote(bandTable, mysql)
                + " ADD COLUMN " + quote("status", mysql)
                + " VARCHAR(20) NOT NULL DEFAULT 'ACCEPTED'");
    }

    private void replaceNameUnique(
            Connection connection,
            String bandTable,
            boolean mysql
    ) throws Exception {
        String nameColumn = findColumn(connection, bandTable, "name");
        if (nameColumn == null) {
            return;
        }

        // name 단일 컬럼 UNIQUE 인덱스를 찾아 제거 (Hibernate 자동 생성 이름 대응)
        for (Map.Entry<String, List<String>> index
                : uniqueIndexes(connection, bandTable).entrySet()) {
            String indexName = index.getKey();
            List<String> columns = index.getValue();

            boolean singleNameUnique = columns.size() == 1
                    && columns.get(0).equalsIgnoreCase(nameColumn);

            if (!singleNameUnique || COMPOSITE_UNIQUE.equalsIgnoreCase(indexName)) {
                continue;
            }

            if (mysql) {
                execute(connection, "ALTER TABLE " + quote(bandTable, mysql)
                        + " DROP INDEX " + quote(indexName, mysql));
            } else {
                try {
                    execute(connection, "ALTER TABLE " + quote(bandTable, mysql)
                            + " DROP CONSTRAINT " + quote(indexName, mysql));
                } catch (Exception ignored) {
                    execute(connection, "DROP INDEX " + quote(indexName, mysql));
                }
            }
        }

        if (!uniqueIndexes(connection, bandTable).containsKey(COMPOSITE_UNIQUE)
                && findUniqueIgnoreCase(connection, bandTable) == null) {
            execute(connection, "ALTER TABLE " + quote(bandTable, mysql)
                    + " ADD CONSTRAINT " + quote(COMPOSITE_UNIQUE, mysql)
                    + " UNIQUE (" + quote(nameColumn, mysql) + ", "
                    + quote("status", mysql) + ")");
        }
    }

    private void createRequestTable(
            Connection connection,
            String bandTable,
            boolean mysql
    ) throws Exception {
        if (findTable(connection, REQUEST_TABLE) != null) {
            return;
        }

        String bandIdColumn = findColumn(connection, bandTable, "id");
        if (bandIdColumn == null) {
            return;
        }

        String idDefinition = mysql
                ? "BIGINT NOT NULL AUTO_INCREMENT"
                : "BIGINT GENERATED BY DEFAULT AS IDENTITY";

        String dateTimeType = mysql
                ? "DATETIME(6)"
                : "TIMESTAMP(6)";

        String sql = "CREATE TABLE " + quote(REQUEST_TABLE, mysql) + " ("
                + quote("id", mysql) + " " + idDefinition + ", "
                + quote("band_id", mysql) + " BIGINT NULL, "
                + quote("requester_id", mysql) + " BIGINT NOT NULL, "
                + quote("band_name", mysql) + " VARCHAR(100) NOT NULL, "
                + quote("discord_message_id", mysql) + " VARCHAR(64) NULL, "
                + quote("rejected_reason", mysql) + " VARCHAR(200) NULL, "
                + quote("processed_by", mysql) + " VARCHAR(100) NULL, "
                + quote("resolved_at", mysql) + " " + dateTimeType + " NULL, "
                + quote("created_at", mysql)
                + " TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, "
                + quote("updated_at", mysql)
                + " TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, "

                + "PRIMARY KEY (" + quote("id", mysql) + "), "

                + "CONSTRAINT " + quote("fk_band_create_request_band", mysql)
                + " FOREIGN KEY (" + quote("band_id", mysql) + ") "
                + "REFERENCES " + quote(bandTable, mysql)
                + " (" + quote(bandIdColumn, mysql) + ") "
                + "ON DELETE SET NULL"
                + ")";

        execute(connection, sql);
    }

    // (name, status) 복합 유니크가 이미 있으면 그 이름을, 없으면 null 반환
    private String findUniqueIgnoreCase(
            Connection connection,
            String bandTable
    ) throws Exception {
        for (Map.Entry<String, List<String>> index
                : uniqueIndexes(connection, bandTable).entrySet()) {
            List<String> columns = index.getValue();
            if (columns.size() == 2
                    && columns.get(0).equalsIgnoreCase("name")
                    && columns.get(1).equalsIgnoreCase("status")) {
                return index.getKey();
            }
        }
        return null;
    }

    private Map<String, List<String>> uniqueIndexes(
            Connection connection,
            String tableName
    ) throws Exception {
        Map<String, List<String>> indexes = new LinkedHashMap<>();

        try (ResultSet rs = connection.getMetaData().getIndexInfo(
                connection.getCatalog(),
                connection.getSchema(),
                tableName,
                true,
                false
        )) {
            while (rs.next()) {
                String indexName = rs.getString("INDEX_NAME");
                String columnName = rs.getString("COLUMN_NAME");

                if (indexName == null || columnName == null) {
                    continue;
                }
                if ("PRIMARY".equalsIgnoreCase(indexName)
                        || indexName.toUpperCase().startsWith("PRIMARY_KEY")) {
                    continue;
                }

                indexes.computeIfAbsent(indexName, k -> new ArrayList<>())
                        .add(columnName);
            }
        }

        return indexes;
    }

    private void execute(Connection connection, String sql) throws Exception {
        try (Statement statement = connection.createStatement()) {
            statement.execute(sql);
        }
    }

    private String findTable(
            Connection connection,
            String expectedName
    ) throws Exception {
        try (ResultSet tables = connection.getMetaData().getTables(
                connection.getCatalog(),
                connection.getSchema(),
                "%",
                new String[]{"TABLE"}
        )) {
            while (tables.next()) {
                String tableName = tables.getString("TABLE_NAME");

                if (expectedName.equalsIgnoreCase(tableName)) {
                    return tableName;
                }
            }
        }

        return null;
    }

    private String findColumn(
            Connection connection,
            String tableName,
            String expectedName
    ) throws Exception {
        try (ResultSet columns = connection.getMetaData().getColumns(
                connection.getCatalog(),
                connection.getSchema(),
                tableName,
                "%"
        )) {
            while (columns.next()) {
                String columnName = columns.getString("COLUMN_NAME");

                if (expectedName.equalsIgnoreCase(columnName)) {
                    return columnName;
                }
            }
        }

        return null;
    }

    private String quote(String identifier, boolean mysql) {
        return mysql
                ? "`" + identifier + "`"
                : "\"" + identifier + "\"";
    }
}
