package db.migration;

import org.flywaydb.core.api.migration.BaseJavaMigration;
import org.flywaydb.core.api.migration.Context;

import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.ResultSet;
import java.sql.Statement;

public class V6__create_session_recruitment_interest extends BaseJavaMigration {

    @Override
    public void migrate(Context context) throws Exception {
        Connection connection = context.getConnection();
        boolean mysql = connection.getMetaData().getDatabaseProductName()
                .toLowerCase()
                .contains("mysql");

        if (findTable(connection, "session_recruitment_interest") != null) {
            return;
        }

        String recruitmentTable = findTable(connection, "session_recruitment");
        String userTable = findTable(connection, "user");
        if (recruitmentTable == null || userTable == null) {
            return;
        }
        String recruitmentIdColumn = findColumn(
                connection,
                recruitmentTable,
                "session_recruitment_id"
        );
        String userIdColumn = findColumn(connection, userTable, "id");
        if (recruitmentIdColumn == null || userIdColumn == null) {
            return;
        }

        String idDefinition = mysql
                ? "BIGINT NOT NULL AUTO_INCREMENT"
                : "BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL";

        String sql = "CREATE TABLE " + quote("session_recruitment_interest", mysql) + " ("
                + quote("session_recruitment_interest_id", mysql) + " " + idDefinition + ", "
                + quote("session_recruitment_id", mysql) + " BIGINT NOT NULL, "
                + quote("user_id", mysql) + " BIGINT NOT NULL, "
                + quote("created_at", mysql) + " TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, "
                + quote("updated_at", mysql) + " TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, "
                + "PRIMARY KEY (" + quote("session_recruitment_interest_id", mysql) + "), "
                + "CONSTRAINT " + quote("uk_session_recruitment_interest", mysql)
                + " UNIQUE (" + quote("session_recruitment_id", mysql) + ", "
                + quote("user_id", mysql) + "), "
                + "CONSTRAINT " + quote("fk_recruitment_interest_recruitment", mysql)
                + " FOREIGN KEY (" + quote("session_recruitment_id", mysql) + ") REFERENCES "
                + quote(recruitmentTable, mysql) + " ("
                + quote(recruitmentIdColumn, mysql) + ") ON DELETE CASCADE, "
                + "CONSTRAINT " + quote("fk_recruitment_interest_user", mysql)
                + " FOREIGN KEY (" + quote("user_id", mysql) + ") REFERENCES "
                + quote(userTable, mysql) + " (" + quote(userIdColumn, mysql) + ") ON DELETE CASCADE"
                + ")";

        try (Statement statement = connection.createStatement()) {
            statement.execute(sql);
        }
    }

    private String findTable(Connection connection, String expectedName) throws Exception {
        DatabaseMetaData metadata = connection.getMetaData();
        try (ResultSet tables = metadata.getTables(
                connection.getCatalog(), connection.getSchema(), "%", new String[]{"TABLE"})) {
            while (tables.next()) {
                String tableName = tables.getString("TABLE_NAME");
                if (expectedName.equalsIgnoreCase(tableName)) {
                    return tableName;
                }
            }
        }
        return null;
    }

    private String findColumn(
            Connection connection,
            String tableName,
            String expectedName
    ) throws Exception {
        DatabaseMetaData metadata = connection.getMetaData();
        try (ResultSet columns = metadata.getColumns(
                connection.getCatalog(), connection.getSchema(), tableName, "%")) {
            while (columns.next()) {
                String columnName = columns.getString("COLUMN_NAME");
                if (expectedName.equalsIgnoreCase(columnName)) {
                    return columnName;
                }
            }
        }
        return null;
    }

    private String quote(String identifier, boolean mysql) {
        return mysql ? "`" + identifier + "`" : "\"" + identifier + "\"";
    }
}
