package db.migration;

import org.flywaydb.core.api.migration.BaseJavaMigration;
import org.flywaydb.core.api.migration.Context;

import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.ResultSet;
import java.sql.Statement;

public class V9__create_session_basic_profile extends BaseJavaMigration {

    @Override
    public void migrate(Context context) throws Exception {
        Connection connection = context.getConnection();
        boolean mysql = connection.getMetaData().getDatabaseProductName()
                .toLowerCase()
                .contains("mysql");

        if (findTable(connection, "session_basic_profiles") != null) {
            return;
        }

        String userTable = findTable(connection, "user");
        if (userTable == null) {
            return;
        }
        String userIdColumn = findColumn(connection, userTable, "id");
        if (userIdColumn == null) {
            return;
        }

        String idDefinition = mysql
                ? "BIGINT NOT NULL AUTO_INCREMENT"
                : "BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL";
        String sql = "CREATE TABLE " + quote("session_basic_profiles", mysql) + " ("
                + quote("session_basic_profile_id", mysql) + " " + idDefinition + ", "
                + quote("user_id", mysql) + " BIGINT NOT NULL, "
                + quote("name", mysql) + " VARCHAR(10), "
                + quote("phone", mysql) + " VARCHAR(11), "
                + quote("email", mysql) + " VARCHAR(255), "
                + quote("gender", mysql) + " VARCHAR(20), "
                + quote("birth_date", mysql) + " DATE, "
                + quote("profile_image_url", mysql) + " VARCHAR(500), "
                + quote("created_at", mysql) + " TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, "
                + quote("updated_at", mysql) + " TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, "
                + "PRIMARY KEY (" + quote("session_basic_profile_id", mysql) + "), "
                + "CONSTRAINT " + quote("uk_session_basic_profile_user", mysql)
                + " UNIQUE (" + quote("user_id", mysql) + "), "
                + "CONSTRAINT " + quote("fk_session_basic_profile_user", mysql)
                + " FOREIGN KEY (" + quote("user_id", mysql) + ") REFERENCES "
                + quote(userTable, mysql) + " (" + quote(userIdColumn, mysql) + ")"
                + ")";

        try (Statement statement = connection.createStatement()) {
            statement.execute(sql);
        }
    }

    private String findTable(Connection connection, String expectedName) throws Exception {
        DatabaseMetaData metadata = connection.getMetaData();
        try (ResultSet tables = metadata.getTables(
                connection.getCatalog(), connection.getSchema(), "%", new String[]{"TABLE"})) {
            while (tables.next()) {
                String tableName = tables.getString("TABLE_NAME");
                if (expectedName.equalsIgnoreCase(tableName)) {
                    return tableName;
                }
            }
        }
        return null;
    }

    private String findColumn(
            Connection connection,
            String tableName,
            String expectedName
    ) throws Exception {
        DatabaseMetaData metadata = connection.getMetaData();
        try (ResultSet columns = metadata.getColumns(
                connection.getCatalog(), connection.getSchema(), tableName, "%")) {
            while (columns.next()) {
                String columnName = columns.getString("COLUMN_NAME");
                if (expectedName.equalsIgnoreCase(columnName)) {
                    return columnName;
                }
            }
        }
        return null;
    }

    private String quote(String identifier, boolean mysql) {
        return mysql ? "`" + identifier + "`" : "\"" + identifier + "\"";
    }
}
